---
address: 0.0.0.0
pid: tmp/pids/thin.pid
wait: 30
port: 4030
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
daemonize: true
servers: 2
chdir: /var/www/current_master
